version: '2'
services:
  php72:
    container_name: php72
    build:
      context: ../../docker/PHP72_APACHE_XDEBUG_SF4
    ports:
      - '80:80'
      - '443:443'
    tty: true
    volumes:
      - ./:/var/www/
